;; Database of gods and such.

(provide 'adnd-gods)

(defconst adnd-gods
  '(("Ala" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Plant" "Weather") ("Divination"))
    ("Ananse" ("All" "Animal" "Charm" "Combat" "Divination" "Healing" "Necromantic" "Protection" "Summoning") ())
    ("Asase Ya" ("All" "Animal" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Plant" "Protection" "Summoning" "Sun" "Weather") ())
    ("Bumba" ("All" "Animal" "Astral" "Charm" "Combat" "Creation" "Divination" "Fire" "Guardian" "Law" "Protection" "Sun" "Wards") ())
    ("Cagn" ("All" "Animal" "Combat" "Divination" "Healing" "Necromantic" "Protection" "Summoning") ())
    ("Eshu" ("All" "Astral" "Charm" "Combat" "Guardian" "Healing" "Necromantic" "Protection") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water"))
    ("Gauna" ("All" "Chaos" "Combat" "Divination" "Guardian" "Necromantic" "Protection" "Time" "Weather") ())
    ("Khonvum" ("All" "Animal" "Creation" "Divination" "Healing" "Necromantic" "Plant" "Summoning") ())
    ("Leza" ("All" "Animal" "Combat" "Divination" "Air" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Weather") ())
    ("Nyame" ("All" "Astral" "Charm" "Combat" "Divination" "Air" "Fire" "Water" "Healing" "Necromantic" "Protection" "Summoning" "Sun" "Wards" "Weather") ())
    ("Obatala" ("All" "Animal" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Plant") ("Guardian" "Healing" "Protection" "Summoning"))
    ("Olokun" ("All" "Animal" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Plant" "Weather") ("Charm" "Divination" "Healing" "Protection"))
    ("Olurun" ("All" "Astral" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Sun" "Weather") ("Animal" "Healing" "Necromantic" "Plant"))
    ("Orunmilla" ("All" "Astral" "Charm" "Creation" "Divination" "Plant" "Protection") ("Combat" "Guardian" "Sun"))
    ("Shango" ("All" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Weather") ("Divination" "Protection"))
    ("So" ("All" "Combat" "Divination" "Air" "Guardian" "Healing" "Necromantic" "Protection" "War" "Weather") ())
    ("Abu-Legba" ("All" "Animal" "Astral" "Divination" "Air" "Protection" "Summoning" "Weather") ())
    ("Animal Priestess" ("All" "Animal" "Combat" "Divination" "Healing" "Protection" "Summoning") ())
    ("Damon-Legba" ("All" "Animal" "Creation" "Divination" "Water" "Protection" "Summoning" "Weather") ())
    ("Heddy-Legba" ("All" "Animal" "Combat" "Divination" "Fire" "Protection" "Summoning" "Sun") ())
    ("Keyan-Legba" ("All" "Animal" "Creation" "Divination" "Earth" "Guardian" "Plant" "Summoning") ())
    ("Obeah-man" ("All" "Astral" "Charm" "Divination" "Healing" "Necromantic" "Protection" "Summoning") ())
    ("Poro" ("All" "Charm" "Divination" "Guardian" "Healing" "Necromantic" "Protection") ())
    ("Witch Doctor" ("Guardian" "Healing" "Necromantic" "Protection" "Weather") ())
    ("Ethoist" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Hakima" ("All" "Divination" "Healing" "Protection" "Sun") ("Charm" "Creation" "Guardian" "Weather"))
    ("Kahin" ("All" "Animal" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Creation" "Protection" "Sun"))
    ("Moralist" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Mystic" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Pragmatist" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Priest-defender" ("All" "Charm" "Combat" "Guardian" "Healing" "Protection" "Wards") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Necromantic" "Sun"))
    ("Shaman" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Protection" "Sun" "Weather") ("Charm" "Combat" "Divination" "Necromantic" "Summoning"))
    ("Dragon Cleric" ("All" "Astral" "Chaos" "Charm" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Summoning" "Thought" "Wards") ())
    ("Sword Knight" ("All" "Combat" "Guardian" "Healing" "Law" "Protection" "War") ("Charm" "Divination" "Sun" "Wards"))
    ("Chemosh" ("All" "Astral" "Combat" "Necromantic" "Thought") ("Healing" "Plant" "Time" "War"))
    ("Hiddukel" ("All" "Chaos" "Guardian" "Summoning" "Time") ("Divination" "Necromantic" "Protection" "Travel"))
    ("Morgion" ("All" "Astral" "Divination" "Healing" "Plant" "Time") ("Necromantic" "Numbers" "Thought"))
    ("Nuitari" ("All" "Astral" "Combat" "Divination" "Guardian" "Healing" "Numbers" "Thought") ("Necromantic" "Protection" "Time" "Weather"))
    ("Sargonnas" ("All" "Astral" "Chaos" "Charm" "Combat" "Summoning" "Thought") ("Creation" "Numbers" "Protection" "Sun" "War"))
    ("Takhsis" ("All" "Astral" "Chaos" "Guardian" "Protection" "Summoning" "Time") ("Combat" "Creation" "Divination" "Healing" "Necromantic" "War" "Wards"))
    ("Zeboim" ("All" "Animal" "Chaos" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Sun" "Weather") ("Protection" "Time" "War"))
    ("Branchala" ("All" "Creation" "Healing" "Numbers" "Plant" "Sun" "Weather") ("Animal" "Charm" "Time" "Travel"))
    ("Habbakuk" ("All" "Animal" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Travel") ("Healing" "Time" "War" "Weather"))
    ("Kiri-Jolith" ("All" "Combat" "Guardian" "Healing" "Law" "Protection" "War") ("Charm" "Divination" "Sun" "Wards"))
    ("Majere" ("All" "Astral" "Charm" "Divination" "Law" "Summoning" "Thought") ("Animal" "Sun" "Travel" "Wards"))
    ("Mishakal" ("All" "Astral" "Charm" "Creation" "Divination" "Healing" "Necromantic" "Numbers" "Sun" "Thought") ("Guardian" "Travel" "Wards"))
    ("Paladine" ("All" "Astral" "Charm" "Guardian" "Healing" "Law" "Protection" "Sun" "Wards") ("Combat" "Thought" "War"))
    ("Solinari" ("All" "Astral" "Combat" "Divination" "Guardian" "Healing" "Thought") ("Numbers" "Protection" "Sun" "Time"))
    ("Chislev" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Sun" "Time" "Weather") ("Chaos" "Charm" "Combat" "Guardian"))
    ("Gilean" ("All" "Astral" "Creation" "Divination" "Healing" "Numbers" "Protection" "Time") ("Animal" "Charm" "Combat" "Sun" "Thought" "Wards"))
    ("Lunitari" ("All" "Astral" "Combat" "Divination" "Guardian" "Healing" "Numbers" "Thought") ("Charm" "Summoning" "Time"))
    ("Reorx" ("All" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Law" "Protection" "Sun" "War") ("Healing" "Summoning" "Thought" "Wards"))
    ("Shinare" ("All" "Charm" "Creation" "Guardian" "Protection" "Travel") ("Combat" "Law" "Sun"))
    ("Sirrion" ("All" "Chaos" "Combat" "Fire" "Guardian" "Healing" "Summoning") ("Numbers" "Sun"))
    ("Zivilyn" ("All" "Astral" "Divination" "Necromantic" "Plant" "Thought") ("Numbers"))
    ("Jijin" ("All" "Animal" "Summoning" "Weather") ("Divination" "Plant"))
    ("Qu'uan" ("All" "Combat" "Divination" "Guardian" "Protection") ("Creation"))
    ("Elf Shaman" ("All" "Animal" "Charm" "Divination" "Healing" "Plant") ("Combat" "Protection"))
    ("Goblin Shaman" ("All" "Combat" "Necromantic" "Protection") ("Divination" "Healing" "Summoning"))
    ("Auril" ("All" "Animal" "Combat" "Divination" "Air" "Earth" "Water" "Healing" "Necromantic" "Protection" "Time" "Weather") ("Creation" "Guardian" "Wards"))
    ("Azuth" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Summoning" "Sun" "Thought" "Wards") ("Elemental" "Air" "Earth" "Fire" "Water" "Travel" "War"))
    ("Beshaba" ("All" "Astral" "Chaos" "Charm" "Combat" "Guardian" "Healing" "Protection" "Summoning" "Wards") ("Creation" "Divination" "Necromantic" "Time"))
    ("Chauntea" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Protection" "Time" "Wards" "Weather") ("Divination" "Travel"))
    ("Curna" ("All" "Charm" "Creation" "Divination" "Healing" "Protection" "Summoning" "Thought" "Travel") ("Guardian" "Necromantic" "Sun" "Wards" "Weather"))
    ("Cyric" ("All" "Astral" "Charm" "Combat" "Guardian" "Healing" "Necromantic" "Summoning" "Sun" "Time" "War" "Weather") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Numbers" "Protection"))
    ("Deneir" ("All" "Astral" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Protection" "Summoning" "Thought") ("Animal" "Plant" "Sun" "Time" "Weather"))
    ("Eldath" ("All" "Animal" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Wards" "Weather") ("Divination" "Travel"))
    ("Gond" ("All" "Astral" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Numbers" "Protection" "Sun") ("Charm" "Creation" "Guardian" "Healing" "Necromantic" "Wards"))
    ("Helm" ("All" "Astral" "Combat" "Divination" "Guardian" "Protection" "Sun" "Wards") ("Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "War"))
    ("Ilmater" ("All" "Charm" "Creation" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Travel") ("Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Sun" "Wards" "Weather"))
    ("Iyachtu Xvim" ("All" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Necromantic" "Summoning" "Thought" "War") ("Creation" "Healing" "Law" "Sun"))
    ("Kelemvor" ("All" "Astral" "Charm" "Combat" "Healing" "Law" "Necromantic" "Summoning" "Time" "Wards") ("Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Travel"))
    ("Lathander" ("All" "Astral" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Plant" "Sun" "Thought" "Wards" "Weather") ("Combat" "Divination" "Guardian" "Time"))
    ("Lliira" ("All" "Animal" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Protection" "Sun" "Travel" "Weather") ("Divination" "Plant" "Summoning" "Thought" "Time"))
    ("Loviatar" ("All" "Charm" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Law" "Necromantic" "Sun") ("Animal" "Divination" "Guardian" "Summoning" "Time" "Weather"))
    ("Lucha" ("All" "Astral" "Divination" "Healing" "Necromantic" "Plant" "Protection" "Sun" "Travel") ("Charm" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Wards"))
    ("Malar" ("All" "Animal" "Combat" "Healing" "Plant" "Summoning" "Sun" "War" "Weather") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Travel"))
    ("Mask" ("All" "Astral" "Charm" "Combat" "Divination" "Guardian" "Healing" "Protection" "Sun" "Time") ("Elemental" "Air" "Earth" "Fire" "Water" "Necromantic" "Summoning" "Thought" "Weather"))
    ("Mielikki D/R" ("All" "Animal" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Wards" "Weather") ("Divination" "Protection" "Travel"))
    ("Mielikki R" () ("Animal" "Plant" "Time" "Travel"))
    ("Milil" ("All" "Astral" "Charm" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Thought") ("Elemental" "Air" "Earth" "Fire" "Water" "Sun" "Travel" "Weather"))
    ("Mystra" ("All" "Astral" "Chaos" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Law" "Necromantic" "Numbers" "Protection" "Summoning" "Thought" "Travel" "Wards") ("Animal" "Plant" "Sun" "Time" "Weather"))
    ("Oghma" ("All" "Astral" "Charm" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Protection" "Summoning" "Thought" "Travel") ("Animal" "Creation" "Necromantic" "Sun" "Wards"))
    ("Selune" ("All" "Animal" "Astral" "Combat" "Divination" "Guardian" "Healing" "Necromantic" "Numbers" "Summoning" "Sun" "Travel" "Weather") ("Charm" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Wards"))
    ("Shar" ("All" "Astral" "Charm" "Combat" "Divination" "Guardian" "Necromantic" "Protection" "Sun" "Thought" "Time") ("Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing"))
    ("Shaundakul" ("All" "Astral" "Combat" "Air" "Healing" "Protection" "Travel" "Weather") ("Animal" "Creation" "Divination" "Earth" "Water" "Guardian" "Necromantic" "Plant" "Sun"))
    ("Silvanus" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Sun" "Time" "Wards" "Weather") ("Divination" "Travel"))
    ("Sune" ("All" "Astral" "Charm" "Creation" "Divination" "Guardian" "Healing" "Protection" "Sun" "Thought" "Time") ("Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Necromantic" "Summoning"))
    ("Talona" ("Astral" "Chaos" "Combat" "Divination" "Guardian" "Healing" "Necromantic" "Summoning") ("All" "Charm" "Protection"))
    ("Talos" ("All" "Animal" "Astral" "Chaos" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Summoning" "Sun" "War" "Weather") ("Creation" "Divination" "Protection" "Time"))
    ("Tempus" ("Animal" "Chaos" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Protection" "War" "Weather") ("All" "Guardian" "Summoning" "Sun" "Wards"))
    ("Torm" ("All" "Astral" "Combat" "Divination" "Guardian" "Healing" "Law" "Protection" "Summoning" "Sun") ("Charm" "Elemental" "Air" "Earth" "Fire" "Water" "Necromantic" "Travel" "Weather"))
    ("Tymora" ("All" "Chaos" "Charm" "Creation" "Divination" "Healing" "Necromantic" "Protection" "Summoning" "Travel") ("Guardian" "Sun" "Wards" "Weather"))
    ("Tyr" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Summoning" "Sun" "War" "Wards") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Umberlee" ("All" "Chaos" "Combat" "Creation" "Water" "Healing" "Necromantic" "Summoning" "Weather") ("Animal" "Charm" "Air" "Earth" "Fire" "Guardian" "Protection" "Sun"))
    ("Amaunator" ("All" "Charm" "Creation" "Air" "Fire" "Law" "Summoning" "Sun" "Time") ("Divination" "Earth" "Healing" "Necromantic" "Numbers" "Protection" "Thought"))
    ("Bane" ("All" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Law" "Necromantic" "Summoning" "War") ("Creation" "Numbers" "Sun"))
    ("Bhaal" ("All" "Astral" "Charm" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Law" "Necromantic" "Summoning") ("Creation" "Divination" "Guardian" "Time"))
    ("Ibrandul" ("All" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection" "Sun" "Travel") ("Chaos" "Combat" "Creation" "Divination" "Healing" "Necromantic"))
    ("Leira" ("All" "Astral" "Charm" "Creation" "Divination" "Healing" "Protection" "Summoning" "Time" "Weather") ("Chaos" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Necromantic"))
    ("Moander" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Plant" "Summoning") ("Animal" "Chaos" "Time" "Weather"))
    ("Myrkul" ("All" "Astral" "Chaos" "Combat" "Guardian" "Healing" "Necromantic" "Summoning" "Time") ("Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "War"))
    ("Akadi" ("Astral" "Air" "Healing" "Protection" "Travel" "Weather") ("Combat" "Divination" "Fire" "Water" "Necromantic"))
    ("Grumbar" ("Combat" "Earth" "Healing" "Protection") ("Divination" "Fire" "Water" "Necromantic" "Travel" "Wards"))
    ("Itishia" ("Animal" "Creation" "Water" "Healing" "Protection" "Weather") ("Combat" "Air" "Earth" "Necromantic" "Numbers" "Time"))
    ("Kossuth" ("Combat" "Fire" "Healing" "Summoning" "Sun") ("Divination" "Air" "Earth" "Protection" "War"))
    ("Gilgeam" ("All" "Charm" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection" "Summoning" "Weather") ("Creation" "Divination" "Necromantic"))
    ("Ramman" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection" "Weather") ("Divination" "Healing" "Necromantic" "Summoning"))
    ("Tiamat" ("All" "Animal" "Charm" "Combat" "Divination" "Guardian" "Necromantic" "Protection" "Weather") ("Elemental" "Air" "Earth" "Fire" "Water" "Summoning"))
    ("Gilgeam" ("All" "Charm" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Law" "Protection" "Summoning" "Weather") ("Creation" "Divination" "Necromantic" "War"))
    ("Tiamat" ("All" "Animal" "Chaos" "Charm" "Combat" "Divination" "Guardian" "Necromantic" "Protection" "Weather") ("Elemental" "Air" "Earth" "Fire" "Water" "Summoning"))
    ("Waukeen" ("Astral" "Charm" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Travel" "Weather") ("All" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Sun" "Wards"))
    ("Cleric" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning") ("Earth" "Water"))
    ("Druid" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Sun" "Weather") ())
    ("Paladin" ("Combat" "Divination" "Healing" "Protection") ())
    ("Ranger" () ("Animal" "Plant"))
    ("Druid - Arctic" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Weather") ("Divination" "Plant"))
    ("Druid - Desert" ("All" "Animal" "Air" "Earth" "Fire" "Healing" "Weather") ("Divination" "Water" "Plant"))
    ("Druid - Forest" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Druid - Gray" ("All" "Animal" "Earth" "Water" "Healing" "Plant") ("Divination" "Air" "Fire" "Weather"))
    ("Druid - Jungle" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Druid - Mountain" ("All" "Animal" "Air" "Earth" "Healing" "Plant" "Weather") ("Divination" "Fire" "Water"))
    ("Druid - Plains" ("All" "Animal" "Air" "Earth" "Fire" "Healing" "Plant" "Weather") ("Divination" "Water"))
    ("Druid - Swamp" ("All" "Animal" "Earth" "Water" "Healing" "Plant" "Weather") ("Divination" "Air" "Fire"))
    ("Crusader - Chaotic" ("All" "Chaos" "Combat" "Guardian" "Healing" "War" "Wards") ("Necromantic" "Protection"))
    ("Crusader - Lawful" ("All" "Combat" "Guardian" "Healing" "Law" "War" "Wards") ("Necromantic" "Protection"))
    ("Monk" ("All" "Divination" "Guardian" "Numbers" "Thought") ("Combat" "Healing" "Necromantic" "Time"))
    ("Sea Priest" ("All" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Weather") ("Animal" "Healing" "Protection"))
    ("Shaman" ("All" "Animal" "Protection" "Summoning" "Travel" "Wards") ("Healing" "Plant"))
    ("Feralan" () ("Animal"))
    ("Greenwood Ranger" () ("Plant"))
    ("Guardian" () ("Animal" "Plant" "Protection"))
    ("Mountain Man" () ("Animal" "Plant"))
    ("Seeker" ("Animal" "Plant") ())
    ("Beory" ("Animal" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Sun" "Weather") ("Charm" "Guardian" "Protection" "Summoning"))
    ("Boccob" ("Astral" "Charm" "Divination" "Numbers" "Thought") ("Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Summoning" "Time"))
    ("Celestian" ("Astral" "Creation" "Sun" "Travel") ("Guardian" "Healing" "Necromantic" "Thought" "Weather"))
    ("Ehlonna" ("Animal" "Charm" "Healing" "Plant" "Sun" "Weather") ("Combat" "Creation" "Air" "Earth" "Water" "Guardian" "Necromantic" "Protection"))
    ("Erythnul" ("Combat" "Healing" "Necromantic" "Summoning") ("Creation" "Protection" "Sun" "War"))
    ("Fharlanghn" ("Air" "Earth" "Summoning" "Travel" "Weather") ("Combat" "Creation" "Healing" "Protection"))
    ("Heironeous" ("Combat" "Guardian" "Healing" "Necromantic" "Protection" "War") ("Summoning" "Sun" "Wards"))
    ("Hextor" ("Combat" "Fire" "Healing" "Law" "Necromantic" "War") ("Summoning" "Sun"))
    ("Incabulos" ("Astral" "Healing" "Necromantic" "Summoning" "Sun") ("Divination"))
    ("Istus" ("Astral" "Divination" "Necromantic" "Thought" "Time") ("Charm" "Guardian" "Healing" "Numbers" "Protection"))
    ("Iuz" ("Chaos" "Charm" "Combat" "Healing" "Necromantic" "Summoning" "Sun") ("Divination"))
    ("Kord" ("All" "Combat" "Summoning") ("Creation" "Healing" "War" "Weather"))
    ("Kord l.9+" ("All" "Combat" "Earth" "Summoning") ("Creation" "Healing" "War" "Weather"))
    ("Lendor" ("Astral" "Divination" "Air" "Law" "Thought" "Time") ("Guardian" "Numbers"))
    ("Mayaheine" ("Combat" "Guardian" "Healing" "Law" "Protection" "Sun" "Wards") ("Charm" "Necromantic"))
    ("Nerull" ("Astral" "Combat" "Guardian" "Healing" "Necromantic" "Sun") ("Charm" "Divination"))
    ("Obad-Hai" ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Sun" "Weather") ("Charm" "Divination" "Necromantic" "Summoning"))
    ("Olidammara" ("Charm" "Creation" "Healing" "Protection") ("Chaos" "Divination" "Travel"))
    ("Pelor" ("Charm" "Creation" "Air" "Guardian" "Healing" "Necromantic" "Protection" "Sun") ("Summoning" "Wards"))
    ("Pholtus" ("Combat" "Divination" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Sun") ("Charm" "Summoning" "War" "Wards"))
    ("Procan" ("Divination" "Air" "Water" "Healing" "Protection" "Summoning" "Weather") ("Animal" "Chaos" "Charm" "Combat" "Plant"))
    ("Ralishaz" ("Chaos" "Charm" "Divination" "Guardian" "Numbers") ("Combat" "Healing" "Summoning" "Thought"))
    ("Rao" ("Astral" "Charm" "Divination" "Guardian" "Healing" "Law" "Thought") ("Necromantic" "Numbers" "Protection" "Wards"))
    ("St. Cuthbert" ("Charm" "Combat" "Divination" "Healing" "Necromantic" "Protection") ("Wards"))
    ("Tharizdun" ("Astral" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Numbers" "Sun" "Thought" "Time") ("Charm" "Wards"))
    ("Trithereon" ("Astral" "Combat" "Guardian" "Healing" "Protection" "Summoning") ("Chaos" "Charm" "Necromantic" "Sun" "Travel"))
    ("Ulaa" ("Combat" "Divination" "Earth" "Fire" "Water" "Guardian" "Healing" "Protection" "Wards") ("Necromantic"))
    ("Wee Jas" ("Astral" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Summoning" "Thought" "Time") ("Combat" "Sun" "Wards"))
    ("Zilchus" ("Charm" "Divination" "Guardian" "Law") ("Healing" "Necromantic" "Protection" "Summoning" "Travel"))
    ("Celtic Bard" () ("All" "Charm" "Divination" "War"))
    ("Celtic Druid" ("All" "Divination" "Healing") ("Animal" "Charm" "Earth" "Water" "Plant" "Weather"))
    ("Manteis" ("Divination") ())
    ("Priest - fantasy" ("All" "Divination" "Healing" "Protection") ("Animal" "Charm" "Necromantic" "Sun" "Weather"))
    ("Priest - hist." ("All" "Healing") ())
    ("Priest - legend" ("All" "Divination" "Healing") ())
    ("Preacher l.10+" ("All" "Healing") ())
    ("Preacher l.2-3" ("All") ())
    ("Preacher l.4-5" ("All") ())
    ("Preacher l.6-7" ("All") ())
    ("Preacher l.8-9" ("All") ())
    ("Christian Cleric" ("All" "Healing") ("Charm" "Necromantic" "Sun"))
    ("Mithraic Priest" ("All" "Astral" "Guardian" "Protection" "Sun") ("Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing"))
    ("Bacchus" ("All" "Charm" "Creation" "Healing" "Plant" "Weather") ())
    ("Ceres" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Cybele" ("All" "Animal" "Divination" "Guardian" "Healing" "Necromantic" "Plant" "Protection") ())
    ("Isis" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Protection" "Sun") ())
    ("Aesculapius" ("All" "Creation" "Divination" "Healing" "Necromantic" "Protection" "Summoning") ("Animal" "Charm" "Guardian" "Plant" "Sun" "Weather"))
    ("Apollo" ("All" "Divination" "Healing" "Sun") ("Charm"))
    ("Bellona" ("Combat" "Healing" "Weather") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Ceres" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Diana" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Hercules" ("All" "Combat" "Healing") ("Elemental" "Air" "Earth" "Fire" "Water" "Necromantic"))
    ("Juno" ("All" "Charm" "Divination" "Healing" "Protection") ("Combat"))
    ("Jupiter" ("All" "Combat" "Healing" "Protection" "Weather") ("Animal" "Divination" "Elemental" "Air" "Earth" "Fire" "Water"))
    ("Mars" ("Combat" "Healing" "Weather") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Mercury" ("All" "Charm" "Healing" "Protection" "Summoning") ("Divination"))
    ("Minerva" ("All" "Charm" "Combat" "Divination" "Healing" "Protection") ())
    ("Neptune" ("All" "Water" "Healing" "Plant" "Weather") ("Animal" "Divination"))
    ("Quirinus" ("All" "Creation" "Healing") ("Combat" "Protection"))
    ("Venus" ("All" "Charm" "Guardian" "Healing") ("Creation"))
    ("Vulcan" ("All" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Sun" "Weather") ())
    ("Shukenja" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun" "Wards") ("Elemental" "Air" "Earth" "Fire" "Water" "Travel" "War"))
    ("Sohei" ("Charm" "Combat" "Guardian" "Protection" "Wards") ())
    ("Coyote" ("All" "Animal" "Charm" "Summoning") ("Chaos" "Travel"))
    ("Earth" ("All" "Animal" "Plant" "Wards") ("Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Weather"))
    ("Fire" ("All" "Chaos" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water") ("Guardian" "Necromantic" "Summoning" "Time" "War"))
    ("Great Spirit" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Protection" "Sun" "Time" "Wards" "Weather") ("Law" "Thought"))
    ("Moon" ("All" "Healing" "Protection" "Wards") ("Charm" "Creation" "Travel" "War"))
    ("Morning Star" ("All" "Creation" "Healing" "Time") ("Animal" "Divination" "Plant" "Protection" "Travel" "Wards"))
    ("Raven" ("All" "Animal" "Charm") ("Time" "Travel"))
    ("Snake" ("All" "Animal" "Charm" "Healing" "Protection") ("Time" "Wards"))
    ("Sun" ("All" "Chaos" "Sun") ("Healing" "Protection" "Thought" "Time"))
    ("Thunder" ("All" "Divination" "Protection" "Time") ("Chaos" "Guardian" "Healing" "Law" "Weather"))
    ("Wind" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Time" "Weather") ("Chaos" "War"))
    ("Centeotl" ("Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Time") ("All" "Chaos" "Weather"))
    ("Chalchihuitlicue" ("All" "Charm" "Creation" "Guardian" "Healing" "Protection" "Time") ("Divination" "Wards" "Weather"))
    ("Huitzilopochtli" ("Combat" "Necromantic" "Sun" "War" "Weather") ("Time" "Travel"))
    ("Ixtlilton" ("Healing" "Necromantic" "Time") ("All" "Protection" "Wards"))
    ("Metzli" ("Animal" "Astral" "Combat" "Necromantic" "Time") ("Protection" "Wards"))
    ("Mictlantecuhtli" ("Combat" "Divination" "Necromantic" "Time") ("Elemental" "Air" "Earth" "Fire" "Water" "Thought" "Wards"))
    ("Ometeotl" ("All" "Animal" "Astral" "Chaos" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Law" "Necromantic" "Numbers" "Plant" "Protection" "Summoning" "Sun" "Thought" "Time" "Travel" "War" "Wards" "Weather") ())
    ("Quetzalcoatl" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun" "Thought") ("Elemental" "Air" "Earth" "Fire" "Water" "Time" "Travel"))
    ("Tezcatlipoca" ("All" "Chaos" "Combat" "Divination" "Necromantic" "Summoning" "Time") ("Elemental" "Air" "Earth" "Fire" "Water" "War"))
    ("Tlaloc" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Law"))
    ("Tlazolteotl" ("Chaos" "Charm" "Divination" "Necromantic") ("Combat" "Healing" "Time"))
    ("Xochipilli" ("All" "Chaos" "Charm" "Creation" "Divination" "Healing") ("Combat" "Travel"))
    ("Xochiquetzal" ("All" "Charm" "Creation" "Healing" "Protection" "Time") ("Chaos" "Divination" "Guardian"))
    ("Arawn" ("All" "Astral" "Creation" "Divination" "Guardian" "Necromantic" "Summoning" "Time") ("Chaos"))
    ("Belenus" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Divination" "Travel"))
    ("Brigantia" ("All" "Animal" "Charm" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Protection" "Time" "Weather") ("Wards"))
    ("Daghdha" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Divination" "Thought" "Wards"))
    ("Diancecht" ("All" "Animal" "Creation" "Divination" "Healing" "Plant" "Protection" "Wards") ("Travel"))
    ("Goibhnin" ("All" "Astral" "Charm" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Protection" "Sun" "Time" "Weather") ("Wards"))
    ("Lugh" ("All" "Animal" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Protection" "Summoning" "Sun" "Travel" "War" "Weather") ())
    ("Manannan mac Lir" ("All" "Animal" "Astral" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Summoning" "Time" "Weather") ("Travel"))
    ("Math Mathonwy" ("All" "Animal" "Astral" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Necromantic" "Plant" "Protection" "Summoning" "Sun" "Thought" "Weather") ("Charm" "Divination" "Healing" "Time"))
    ("Morrigan" ("All" "Astral" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection" "War") ("Chaos"))
    ("Oghma" ("All" "Animal" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Protection" "Summoning" "Sun" "Wards") ("Thought" "Time"))
    ("Ch'eng Huang" ("All" "Charm" "Divination" "Guardian" "Protection") ("Elemental" "Air" "Earth" "Fire" "Water" "Healing"))
    ("Chih-Nii" ("All" "Charm" "Healing" "Numbers" "Protection" "Summoning") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Thought"))
    ("Chung Kuel" ("All" "Divination" "Healing" "Numbers" "Protection") ("Charm" "Summoning" "Thought" "Time"))
    ("Fu Hsing" ("All" "Chaos" "Charm" "Creation" "Healing") ("Time" "Travel"))
    ("K'ung Fu-tzu" ("All" "Charm" "Healing" "Law") ("Guardian" "Protection"))
    ("Kuan Yin" ("All" "Charm" "Creation" "Healing" "Protection" "Wards") ("Guardian" "Travel"))
    ("Kuan-ti" ("All" "Combat" "Guardian" "Protection" "War" "Wards") ("Healing" "Thought" "Time"))
    ("Lao Tsu" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Thought" "Weather") ("Divination"))
    ("Lei Kung" ("All" "Elemental" "Air" "Earth" "Fire" "Water" "Law" "Weather") ("Combat" "Sun" "War"))
    ("Liu" ("All" "Healing" "Plant" "Sun" "Time" "Weather") ("Animal" "Wards"))
    ("Lu Hsing" ("All" "Charm" "Divination" "Healing" "Law" "Sun") ("Wards"))
    ("Shang-ti" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Summoning" "Sun" "Thought") ("Elemental" "Air" "Earth" "Fire" "Water" "War" "Wards"))
    ("Shou Hsing" ("All" "Astral" "Creation" "Healing" "Necromantic" "Protection" "Time") ("Chaos" "Charm" "Combat"))
    ("Sung Chiang" ("Charm" "Combat" "Guardian" "Necromantic" "Time") ("Divination" "Healing" "Wards"))
    ("Yen-Wang-Yeh" ("All" "Law" "Necromantic" "Protection") ("Divination" "Summoning" "Time" "Wards"))
    ("Anhur" ("All" "Combat" "Sun" "War") ("Guardian" "Healing" "Necromantic" "Protection" "Time"))
    ("Bast" ("All" "Animal" "Charm" "Summoning" "Time") ("Combat" "Healing" "Protection" "Travel"))
    ("Geb" ("All" "Astral" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection" "Summoning" "Time") ("Combat" "Creation" "Wards"))
    ("Horus" ("All" "Combat" "Sun" "War") ("Guardian" "Healing" "Necromantic" "Protection" "Wards"))
    ("Isis" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Numbers" "Protection" "Sun") ("Necromantic" "Time"))
    ("Nephythys" ("All" "Charm" "Combat" "Guardian" "Healing" "Numbers" "Protection" "Sun") ("Wards" "Weather"))
    ("Nut" ("All" "Astral" "Charm" "Divination" "Guardian" "Protection" "Time" "Weather") ("Healing" "Wards"))
    ("Osiris" ("All" "Astral" "Guardian" "Healing" "Necromantic" "Protection" "Wards") ("Charm" "Combat" "Thought"))
    ("Ptah" ("All" "Astral" "Charm" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Sun" "Travel") ("Summoning" "Time"))
    ("Ra" ("All" "Astral" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Law" "Sun" "Thought") ("Time" "Wards" "Weather"))
    ("Set" ("All" "Astral" "Chaos" "Combat" "Guardian" "Necromantic" "Summoning") ("Healing" "Protection" "Time"))
    ("Shu" ("All" "Astral" "Elemental" "Air" "Earth" "Fire" "Water" "Sun" "Time") ("Guardian" "Protection" "Wards" "Weather"))
    ("Tefnut" ("All" "Astral" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Sun" "Time" "Weather") ("Charm" "Divination" "Wards"))
    ("Thoth" ("All" "Astral" "Charm" "Guardian" "Healing" "Numbers" "Protection" "Sun") ("Divination" "Thought" "Weather"))
    ("Aphrodite" ("All" "Charm" "Guardian" "Healing" "Time") ("Chaos" "Creation"))
    ("Apollo" ("All" "Divination" "Healing" "Sun") ("Charm" "Thought" "Time"))
    ("Ares" ("Chaos" "Combat" "Healing" "War" "Weather") ("Elemental" "Air" "Earth" "Fire" "Water"))
    ("Artemis" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination" "Time" "Travel"))
    ("Athena" ("All" "Charm" "Combat" "Divination" "Healing" "Protection" "War") ("Numbers" "Wards"))
    ("Demeter" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination" "Time" "Travel"))
    ("Dionysus" ("All" "Charm" "Creation" "Healing" "Plant") ("Chaos" "Time" "Weather"))
    ("Gaea" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Divination"))
    ("Hades" ("All" "Charm" "Creation" "Divination" "Healing" "Necromantic" "Protection" "Summoning") ("Law" "Time"))
    ("Hephaestus" ("All" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Sun" "Weather") ("Thought" "Wards"))
    ("Hera" ("All" "Chaos" "Charm" "Divination" "Healing" "Protection") ("Combat" "Wards"))
    ("Hermes" ("All" "Charm" "Healing" "Protection" "Summoning" "Travel") ("Chaos" "Divination" "Time"))
    ("Poseidon" ("All" "Water" "Healing" "Plant" "Weather") ("Animal" "Chaos" "Divination" "Time"))
    ("Rhea" ("All" "Animal" "Charm" "Guardian" "Healing" "Plant" "Protection" "Time") ("Creation"))
    ("Uranus" ("Astral" "Chaos" "Combat" "Protection") ("Divination" "Healing"))
    ("Zeus" ("All" "Combat" "Healing" "Law" "Protection" "Weather") ("Animal" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Wards"))
    ("Agni" ("All" "Chaos" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Sun") ("Creation" "Time" "Travel"))
    ("Brihaspati" ("All" "Charm" "Divination" "Healing" "Protection" "Thought") ("Law" "Wards"))
    ("Indra" ("Chaos" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "War" "Weather") ("Summoning" "Time"))
    ("Kali" ("All" "Chaos" "Charm" "Combat" "Creation" "Healing" "Necromantic") ("Thought" "Time"))
    ("Mitra" ("All" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Law" "Plant" "Protection" "Sun") ("Divination" "Thought" "Travel"))
    ("Puchan" ("All" "Charm" "Combat" "Creation" "Healing" "Protection" "Summoning" "Travel") ("Divination" "Time" "Wards"))
    ("Ratri" ("All" "Astral" "Charm" "Guardian" "Healing" "Necromantic" "Protection" "Summoning") ("Chaos" "Divination" "Time"))
    ("Rudra" ("All" "Animal" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Time" "Weather") ("Numbers" "Thought"))
    ("Savitri" ("All" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Sun" "Time") ("Divination" "Travel" "Wards"))
    ("Siva" ("All" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Necromantic" "Sun" "Time" "Weather") ("Numbers" "Thought"))
    ("Soma" ("All" "Chaos" "Divination" "Healing" "Plant" "Protection") ("Animal" "Charm" "Thought" "Time"))
    ("Surya" ("All" "Divination" "Healing" "Law" "Protection" "Sun") ("Charm" "Time" "Wards"))
    ("Tvashtri" ("All" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Protection" "Summoning") ("Divination" "Numbers" "Thought"))
    ("Ushas" ("All" "Charm" "Creation" "Guardian" "Healing" "Law" "Protection" "Sun") ("Divination" "Time" "Wards"))
    ("Varuna" ("All" "Astral" "Charm" "Divination" "Healing" "Law" "Protection" "Sun") ("Combat" "Guardian" "Thought" "Wards"))
    ("Vayu" ("All" "Astral" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Protection" "Weather") ("Time" "Wards"))
    ("Yama" ("All" "Healing" "Law" "Necromantic") ("Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Thought" "Time"))
    ("Ama-Tsu-Mara" ("All" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Sun" "Time") ("Combat"))
    ("Amaterasu" ("All" "Astral" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Sun" "Time" "Wards") ("Creation"))
    ("Amatsu-Mikaboshi" ("All" "Charm" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Time") ())
    ("Hachiman" ("All" "Combat" "Healing" "Travel" "War" "Weather") ("Divination"))
    ("Ho Masubi" ("All" "Creation" "Healing" "Plant" "Sun" "Time") ("Combat"))
    ("Inari" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Divination"))
    ("Izanagi" ("All" "Animal" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Time" "Travel") ())
    ("Izanami" ("All" "Animal" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Time" "Travel") ())
    ("Kura Okami" ("All" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Time" "Weather") ())
    ("Nai No Kami" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Summoning" "Time" "Weather") ("Divination"))
    ("O-Kuni-Nushi" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Divination"))
    ("O-Wata-Tsu-Mi" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Time" "Weather") ("Divination"))
    ("Raiden" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Summoning" "Time" "Weather") ())
    ("Shichifukujin" ("All" "Charm" "Creation" "Divination" "Guardian" "Healing" "Protection" "Weather") ())
    ("Shina-Tsu-Hiko" ("All" "Astral" "Chaos" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Protection" "Summoning" "Weather") ())
    ("Susanoo" ("All" "Chaos" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Sun" "Weather") ("Divination"))
    ("Tsuki-Yomi" ("Charm" "Divination" "Healing" "Necromantic" "Numbers" "Sun" "Time") ("Creation"))
    ("Gods of Trouble" ("All" "Chaos" "Charm" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning") ())
    ("Hate" ("All" "Chaos" "Charm" "Combat" "Summoning") ())
    ("Issek of the Jug" ("All" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Wards") ())
    ("Kos" ("All" "Combat" "Divination" "Healing" "Law" "Protection") ())
    ("Red God" ("All" "Combat" "Healing" "Protection" "Sun" "War" "Weather") ("Wards"))
    ("Tyaa" ("All" "Animal" "Summoning" "Time") ())
    ("Aegir" ("All" "Chaos" "Weather") ("Divination" "Guardian" "Time"))
    ("Baldur" ("All" "Charm" "Divination" "Protection" "Summoning" "Thought") ("Time"))
    ("Bragi" ("All" "Charm" "Divination" "Healing" "Protection" "Thought") ("Travel"))
    ("Forseti" ("All" "Charm" "Combat" "Divination" "Law" "Protection") ("Thought"))
    ("Frey" ("All" "Animal" "Charm" "Divination" "Protection" "Sun" "Time" "Weather") ("Wards"))
    ("Freya" ("All" "Animal" "Chaos" "Charm" "Creation" "Divination" "Healing" "Necromantic") ("Time"))
    ("Frigga" ("All" "Charm" "Creation" "Divination" "Law" "Plant" "Sun" "Weather") ("Animal" "Time"))
    ("Heimdall" ("All" "Combat" "Divination" "Guardian" "Protection" "Summoning" "Sun" "Wards") ("Law"))
    ("Hel" ("All" "Charm" "Divination" "Healing" "Necromantic" "Time") ("Creation" "Numbers"))
    ("Idun" ("All" "Animal" "Charm" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic" "Plant" "Time" "Weather") ("Divination" "Travel"))
    ("Loki" ("All" "Chaos" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Summoning") ("Time"))
    ("Odin" ("All" "Combat" "Divination" "Protection" "Summoning" "Thought" "Time" "War") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Wards"))
    ("Sif" ("All" "Charm" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Time") ("Divination" "Summoning" "Wards"))
    ("Surtr" ("Charm" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection") ("Time" "War" "Wards"))
    ("Thor" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Sun" "Time" "Weather") ("Charm" "Wards"))
    ("Thyrm" ("Charm" "Divination" "Healing" "Protection" "Weather") ("Time" "War" "Wards"))
    ("Tyr" ("All" "Combat" "Divination" "Guardian" "Healing" "Law" "Protection") ("Wards"))
    ("Valkyries" ("Charm" "Combat" "Healing") ())
    ("Azul" ("Elemental" "Air" "Earth" "Fire" "Water" "Weather") ("Charm" "Creation" "Protection"))
    ("Eha" ("Elemental" "Air" "Earth" "Fire" "Water") ("Charm" "Divination" "Healing" "Weather"))
    ("Kiltzi" ("Charm" "Creation" "Guardian" "Healing" "Protection") ("Animal" "Plant" "Weather"))
    ("Maztica" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Nula" ("Animal" "Combat" "Guardian" "Protection") ("Plant" "Sun" "Weather"))
    ("Plutoq" ("Elemental" "Air" "Earth" "Fire" "Water") ("Creation" "Guardian" "Protection"))
    ("Qotal" ("Creation" "Healing" "Protection") ("Animal" "Astral" "Divination" "Plant"))
    ("Tezca" ("Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Sun" "Weather") ("Animal" "Divination" "Guardian"))
    ("Watil" ("Creation" "Healing" "Plant") ("Animal" "Divination" "Guardian"))
    ("Zaltec" () ("Charm" "Combat" "Sun"))
    ("Hishnashaper" () ())
    ("Plumaweaver" () ())
    ("God of Pestilence" ("All" "Animal" "Healing" "Necromantic" "Summoning" "Weather") ("Combat" "Divination" "Protection"))
    ("God of Suffering" ("All" "Charm" "Guardian" "Healing" "Necromantic" "Protection") ("Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Sun" "Travel" "Weather"))
    ("God of the Dead" ("All" "Astral" "Divination" "Necromantic" "Protection" "Travel") ("Charm" "Combat" "Guardian" "Healing" "Summoning" "Sun"))
    ("Goddess of Murder" ("All" "Chaos" "Charm" "Healing" "Necromantic") ("Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Protection"))
    ("Lord of Undead" ("All" "Astral" "Charm" "Necromantic" "Summoning" "Thought") ("Combat" "Divination" "Protection" "Sun"))
    ("Asmodeus" ("All" "Charm" "Combat" "Divination" "Healing") ("Animal" "Necromantic" "Protection" "Sun"))
    ("Baalzebul" ("All" "Charm" "Combat" "Protection") ("Divination" "Healing" "Necromantic" "Sun"))
    ("Brogine" ("All" "Divination" "Healing" "Plant" "Protection" "Summoning" "Weather") ("Animal" "Combat" "Creation" "Guardian" "Necromantic" "Sun"))
    ("Creegus" ("All" "Animal" "Combat" "Summoning" "War") ("Divination" "Guardian" "Necromantic" "Protection"))
    ("Da'har Su'revar" ("All" "Charm" "Divination" "Necromantic" "Summoning" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection"))
    ("Elondar" ("All" "Animal" "Astral" "Summoning" "Sun" "Weather") ("Combat" "Divination" "Guardian" "Healing" "Plant"))
    ("Frenzick" ("All" "Combat" "Air" "Guardian" "War") ("Creation" "Healing" "Necromantic" "Protection" "Sun"))
    ("Frethenti" ("All" "Creation" "Divination" "Water" "Plant" "Wards") ("Animal" "Healing" "Protection" "Sun" "Weather"))
    ("Gadraka" ("All" "Combat" "Divination" "War") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Necromantic"))
    ("Garjarvan" ("Elemental" "Air" "Earth" "Fire" "Water" "Travel" "Weather") ("Healing" "Protection"))
    ("Lyganver" ("All" "Divination" "Healing" "Numbers" "Protection" "Summoning") ("Combat" "Creation" "Necromantic" "Sun" "Weather"))
    ("Manitaga" ("All" "Charm" "Healing" "Necromantic" "Protection") ("Creation" "Divination" "Guardian" "Sun"))
    ("Neodig Beowulf" ("All" "Divination" "Healing" "Necromantic" "Numbers" "Thought" "Travel") ("Charm" "Creation" "Law" "Protection" "Time" "Wards"))
    ("Orcus" ("All" "Combat" "Guardian" "Healing" "Necromantic" "Sun") ("Divination"))
    ("Orin" ("Elemental" "Air" "Earth" "Fire" "Water" "Travel" "Weather") ("Healing" "Protection"))
    ("Setesh" ("All" "Combat" "Guardian" "Healing" "Necromantic" "Protection" "Weather") ())
    ("Tilvaretu" ("All" "Charm" "Healing" "Summoning") ("Combat" "Guardian" "Numbers" "War"))
    ("Tobrig" ("All" "Combat" "Creation" "Earth" "Fire" "Protection") ("Divination" "Air" "Water" "Healing" "Sun"))
    ("Ulbreg" ("All" "Combat" "Healing" "Necromantic" "War") ("Divination" "Guardian" "Protection" "Summoning"))
    ("Zattaze" ("All" "Animal" "Astral" "Chaos" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Law" "Necromantic" "Numbers" "Plant" "Protection" "Summoning" "Sun" "Thought" "Time" "Travel" "War" "Wards" "Weather") ())
    ("Cthugha" ("All" "Combat" "Fire" "Summoning") ())
    ("Cthulhu" ("All" "Combat" "Water" "Necromantic" "Weather") ("Divination" "Summoning"))
    ("Hastur" ("All" "Combat" "Air" "Weather") ())
    ("Ithaqua" ("All" "Combat" "Air" "Summoning" "Weather") ())
    ("Shub-Nigurrath" ("All" "Animal" "Charm" "Creation" "Earth" "Healing" "Plant") ("Combat" "Weather"))
    ("Yog-Sothoth" ("All" "Astral" "Divination" "Necromantic" "Summoning" "Time") ("Combat" "Numbers" "Weather"))
    ("Anteros" ("All" "Charm" "Healing" "Protection" "Sun" "Thought") ("Animal" "Divination" "Weather"))
    ("Aurora" ("All" "Astral" "Charm" "Divination" "Air" "Fire" "Healing" "Summoning" "Sun") ("Animal" "Creation" "Necromantic" "Plant" "Protection" "Time" "Weather"))
    ("Chaos" ("All" "Astral" "Chaos" "Creation") ("Elemental" "Air" "Earth" "Fire" "Water" "Numbers" "Time"))
    ("Enyo" ("All" "Combat" "Healing" "War") ("Chaos" "Necromantic" "Protection"))
    ("Eris" ("All" "Chaos" "Combat" "Necromantic") ("Animal" "Healing" "War" "Weather"))
    ("Eros" ("All" "Animal" "Charm" "Healing" "Necromantic" "Protection" "Summoning" "Thought") ("Creation" "Divination" "Guardian" "Plant" "Sun" "Weather"))
    ("Hebe" ("All" "Animal" "Charm" "Healing" "Necromantic" "Plant" "Protection" "Time") ("Divination" "Sun" "Wards"))
    ("Hestia" ("All" "Creation" "Guardian" "Healing" "Protection" "Wards") ("Animal" "Divination" "Fire" "Plant"))
    ("Hyperion" ("All" "Divination" "Plant" "Sun") ("Charm" "Air" "Fire" "Healing" "Necromantic" "Protection"))
    ("Hypnos" ("All" "Astral" "Charm" "Divination" "Healing" "Thought" "Time") ("Animal" "Air" "Earth" "Water" "Necromantic" "Protection"))
    ("Iris" ("All" "Creation" "Divination" "Air" "Water" "Sun" "Weather") ("Healing" "Numbers" "Plant" "Protection" "Thought" "Wards"))
    ("Mnemosyne" ("All" "Astral" "Charm" "Divination" "Law" "Numbers" "Thought" "Time") ("Creation" "Necromantic" "Plant" "Protection"))
    ("Morpheus" ("All" "Charm" "Divination" "Guardian" "Healing" "Protection" "Thought" "Wards") ("Astral" "Chaos" "Necromantic" "Numbers" "Sun" "Time" "Travel"))
    ("Oceanus" ("All" "Animal" "Divination" "Water" "Weather") ("Chaos" "Charm" "Combat" "Plant" "Protection" "War"))
    ("Pan" ("All" "Animal" "Chaos" "Charm" "Summoning") ("Astral" "Divination" "Healing" "Plant" "Protection"))
    ("Phobos" ("All" "Chaos" "Combat" "Necromantic") ("Charm" "Healing" "Protection"))
    ("Thanatos" ("All" "Astral" "Charm" "Divination" "Necromantic" "Protection") ("Chaos" "Guardian" "Sun" "Time" "Weather"))
    ("Themis" ("All" "Guardian" "Healing" "Law" "Thought") ("Protection" "Time"))
    ("Sklarnherra" ("All" "Chaos" "Earth" "Fire" "Healing" "War") ("Combat" "Necromantic"))
    ("U'llek Yot" ("All" "Combat" "Healing" "Protection" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Wards"))
    ("Aphyx" ("All" "Creation" "Divination" "Healing" "Necromantic" "Summoning") ("Combat" "Sun"))
    ("Bhon" ("All" "Animal" "Creation" "Guardian" "Healing" "Plant" "Protection") ("Combat" "Divination" "Sun" "Travel"))
    ("Cyr - chaotic" ("All" "Combat" "Healing") ("Chaos" "Elemental" "Air" "Earth" "Fire" "Water" "War"))
    ("Cyr - lawful" ("All" "Combat" "Healing") ("Elemental" "Air" "Earth" "Fire" "Water" "Law" "War"))
    ("Eregul" ("All" "Astral" "Divination" "Healing" "Necromantic" "Time") ("Protection" "Sun"))
    ("Flor" ("All" "Creation" "Divination" "Healing" "Necromantic" "Protection" "Summoning" "Time" "Travel" "Wards") ("Charm" "Guardian" "Plant" "Sun"))
    ("Hubris" ("Combat" "Law" "War") ("Healing" "Necromantic" "Protection"))
    ("Ibrahil" ("All" "Combat" "Creation" "Divination" "Guardian" "Law" "Protection") ("Healing" "Necromantic"))
    ("Kaeal" ("All" "Astral" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Numbers" "Summoning" "Thought" "Wards") ("Animal" "Guardian" "Necromantic" "Plant" "Protection" "Sun" "Weather"))
    ("Kir" ("All" "Animal" "Water" "Plant" "Protection" "Summoning" "Travel" "Weather") ("Creation" "Divination"))
    ("Lisori" ("All" "Charm" "Creation" "Divination" "Guardian" "Healing" "Protection" "Sun" "Travel" "Wards") ("Necromantic"))
    ("Lukane" ("All" "Chaos" "Charm" "Creation" "Divination" "Numbers" "Sun" "Time") ("Combat" "Protection"))
    ("Nethlar" ("All" "Astral" "Divination" "Numbers" "Protection" "Summoning" "Thought" "Time") ("Combat" "Guardian" "Healing" "Sun"))
    ("Orion" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Sun" "Travel") ("Guardian" "Healing" "Protection" "Weather"))
    ("Othmus" ("All" "Astral" "Charm" "Divination" "Numbers" "Summoning" "Thought" "Time") ("Guardian" "Protection" "Sun"))
    ("Rushlyn" ("All" "Charm" "Creation" "Healing" "Protection" "Sun") ("Combat" "Divination" "Guardian"))
    ("S'yl" ("All" "Animal" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Sun" "Time" "Weather") ("Divination" "Protection"))
    ("Tabrahil" ("All" "Astral" "Chaos" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Sun" "Weather") ())
    ("Tengri" ("All" "Astral" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Summoning" "Sun" "Weather") ("Charm" "Healing"))
    ("Solarus" ("All" "Combat" "Creation" "Fire" "Guardian" "Healing" "Necromantic" "Protection" "Sun") ("Divination" "Wards" "Weather"))
    ("Agricolture God" ("All" "Creation" "Divination" "Plant" "Summoning") ("Animal" "Healing" "Protection" "Sun" "Weather"))
    ("Ancestors God" ("All" "Astral" "Creation" "Divination" "Guardian" "Necromantic" "Protection") ("Charm" "Healing"))
    ("Animals God" ("All" "Animal" "Charm" "Divination" "Protection") ("Combat" "Creation" "Healing" "Plant"))
    ("Arts God" ("All" "Astral" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Protection" "Sun") ("Healing" "Necromantic"))
    ("Birth God" ("All" "Astral" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Summoning" "Sun") ("Animal" "Combat" "Divination" "Guardian" "Necromantic"))
    ("Children God" ("All" "Astral" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Summoning" "Sun") ("Animal" "Combat" "Divination" "Guardian" "Necromantic"))
    ("Community God" ("All" "Creation" "Healing") ("Combat" "Protection"))
    ("Competition God" ("All" "Divination" "Elemental" "Air" "Earth" "Fire" "Water") ("Combat" "Healing"))
    ("Crafts God" ("All" "Creation" "Divination" "Healing") ("Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Plant" "Protection" "Sun"))
    ("Culture God" ("All" "Charm" "Divination") ("Combat" "Creation"))
    ("Dance God" ("All" "Animal" "Charm" "Summoning" "Sun") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant"))
    ("Darkness God" ("All" "Charm" "Divination" "Necromantic" "Summoning" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection"))
    ("Dawn God" ("All" "Charm" "Divination" "Air" "Fire" "Healing" "Summoning" "Sun") ("Animal" "Creation" "Necromantic" "Plant" "Protection" "Weather"))
    ("Death God" ("All" "Astral" "Charm" "Divination" "Protection") ("Guardian" "Necromantic" "Sun" "Weather"))
    ("Destiny God" ("All" "Divination" "Guardian" "Protection" "Summoning") ("Combat" "Necromantic" "Sun" "Weather"))
    ("Disease God" ("All" "Animal" "Healing" "Summoning" "Weather") ("Combat" "Divination" "Necromantic" "Protection"))
    ("Dwarven Race God" ("All" "Combat" "Protection") ("Divination" "Healing"))
    ("Earth God" ("All" "Creation" "Earth" "Plant" "Summoning") ("Animal" "Divination" "Healing" "Protection"))
    ("Elemental Force God" ("All" "Combat" "Elemental" "Air" "Earth" "Fire" "Water") ("Creation" "Sun" "Weather"))
    ("Elven Race God" ("All" "Plant" "Summoning") ("Healing" "Sun"))
    ("Everything God" ("All" "Creation" "Healing") ("Divination" "Protection"))
    ("Evil Philosophy" ("All" "Charm" "Necromantic") ("Animal" "Protection"))
    ("Fate God" ("All" "Divination" "Guardian" "Protection" "Summoning") ("Combat" "Necromantic" "Sun" "Weather"))
    ("Fertility God" ("All" "Healing" "Necromantic" "Plant" "Summoning") ("Animal" "Charm" "Creation" "Divination" "Protection" "Weather"))
    ("Fire God" ("All" "Fire" "Sun") ("Charm" "Divination" "Healing" "Necromantic" "Protection" "Weather"))
    ("Fortune God" ("All" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Summoning") ("Animal" "Creation" "Guardian" "Plant" "Sun" "Weather"))
    ("Gnome Race God" ("All" "Plant" "Protection") ("Divination" "Healing"))
    ("Good Philosophy" ("All" "Healing" "Protection") ("Charm" "Divination"))
    ("Guardianship God" ("All" "Necromantic" "Protection") ("Guardian" "Healing"))
    ("Halfling Race God" ("All" "Creation" "Divination" "Guardian" "Protection") ("Charm" "Healing" "Necromantic" "Sun"))
    ("Healing God" ("All" "Creation" "Divination" "Healing" "Necromantic" "Protection" "Summoning") ("Animal" "Charm" "Guardian" "Plant" "Sun" "Weather"))
    ("Human Race God" ("All" "Divination" "Healing") ("Necromantic" "Sun"))
    ("Hunting God" ("All" "Divination" "Guardian" "Protection" "Summoning") ("Animal" "Healing" "Plant" "Weather"))
    ("Justice God" ("All" "Divination" "Necromantic") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian"))
    ("Kingship God" ("All" "Charm" "Elemental" "Air" "Earth" "Fire" "Water") ("Healing" "Protection"))
    ("Life-Death-Rebirth" ("All" "Divination" "Healing" "Necromantic" "Plant" "Summoning" "Weather") ("Animal" "Charm" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Sun"))
    ("Light God" ("All" "Charm" "Divination" "Healing" "Sun") ("Animal" "Creation" "Necromantic" "Plant"))
    ("Lightning God" ("All" "Air" "Fire" "Weather") ("Divination" "Plant"))
    ("Literature God" ("All" "Charm" "Creation" "Divination" "Protection" "Summoning" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Plant"))
    ("Love God" ("All" "Animal" "Charm" "Healing" "Necromantic" "Protection" "Summoning") ("Creation" "Divination" "Guardian" "Plant" "Sun" "Weather"))
    ("Luck God" ("All" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Summoning") ("Animal" "Creation" "Guardian" "Plant" "Sun" "Weather"))
    ("Magic God" ("All" "Astral" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Protection" "Summoning") ("Animal" "Guardian" "Necromantic" "Plant" "Sun" "Weather"))
    ("Mankind Philosophy" ("All" "Charm" "Healing") ("Combat" "Creation" "Divination" "Protection"))
    ("Marriage God" ("All" "Charm" "Divination" "Healing" "Protection") ("Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Sun"))
    ("Messengers God" ("All" "Charm" "Divination" "Protection" "Sun") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Necromantic" "Plant"))
    ("Metalwork God" ("All" "Fire" "Sun") ("Combat" "Divination"))
    ("Mischief God" ("Charm" "Divination" "Protection" "Summoning") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Plant"))
    ("Moon God" ("All" "Charm" "Divination" "Summoning" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Necromantic"))
    ("Music God" ("All" "Animal" "Charm" "Summoning" "Sun") ("Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant"))
    ("Nature God" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Protection") ("Divination" "Healing" "Sun" "Weather"))
    ("Night God" ("All" "Charm" "Divination" "Necromantic" "Summoning" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Protection"))
    ("Oceans God" ("All" "Animal" "Divination" "Water" "Weather") ("Charm" "Combat" "Plant" "Protection"))
    ("Oracles Gog" ("All" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Summoning") ("Charm" "Creation" "Necromantic" "Sun"))
    ("Peace God" ("All" "Charm" "Creation" "Divination" "Protection") ("Animal" "Guardian" "Healing" "Necromantic"))
    ("Poetry God" ("All" "Charm" "Creation" "Divination" "Protection" "Summoning" "Sun") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Plant"))
    ("Prophecy Gog" ("All" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Summoning") ("Charm" "Creation" "Necromantic" "Sun"))
    ("Prosperity God" ("All" "Animal" "Creation" "Plant" "Summoning") ("Guardian" "Healing" "Necromantic" "Protection"))
    ("Redemption God" ("All" "Charm" "Combat") ("Divination" "Healing"))
    ("Revenge God" ("All" "Divination" "Necromantic") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian"))
    ("Rivers God" ("All" "Animal" "Divination" "Water" "Weather") ("Charm" "Combat" "Plant" "Protection"))
    ("Rulership God" ("All" "Charm" "Elemental" "Air" "Earth" "Fire" "Water") ("Healing" "Protection"))
    ("Seasons God" ("All" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Weather") ("Animal" "Divination" "Healing" "Plant"))
    ("Sites God" ("All" "Healing" "Protection") ("Animal" "Plant"))
    ("Sky God" ("All" "Astral" "Air" "Water" "Protection" "Weather") ("Combat" "Divination" "Plant" "Sun"))
    ("Strength God" ("All" "Combat" "Healing") ("Elemental" "Air" "Earth" "Fire" "Water" "Necromantic"))
    ("Sun God" ("All" "Divination" "Healing" "Necromantic" "Sun") ("Charm" "Fire" "Plant" "Protection"))
    ("Thunder God" ("All" "Combat" "Weather") ("Divination" "Protection"))
    ("Time God" ("All" "Astral" "Divination" "Healing" "Necromantic") ("Plant" "Protection" "Sun" "Weather"))
    ("Trade God" ("All" "Charm" "Divination" "Guardian" "Protection") ("Combat" "Healing" "Sun" "Weather"))
    ("Trickery God" ("Charm" "Divination" "Protection" "Summoning") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Plant"))
    ("Vegetation God" ("All" "Divination" "Healing" "Plant" "Protection" "Summoning" "Weather") ("Animal" "Combat" "Creation" "Guardian" "Necromantic" "Sun"))
    ("War God" ("Combat" "Healing") ("Necromantic" "Protection"))
    ("Weather God" ("All" "Astral" "Air" "Water" "Protection" "Weather") ("Combat" "Divination" "Plant" "Sun"))
    ("Wind God" ("All" "Air" "Protection" "Weather") ("Divination" "Guardian"))
    ("Wisdom God" ("All" "Charm" "Divination") ("Healing" "Sun"))
    ("Ancestors God" ("All" "Astral" "Creation" "Divination" "Guardian" "Necromantic" "Protection") ("Charm" "Healing" "Time"))
    ("Community God" ("All" "Creation" "Healing" "Wards") ("Combat" "Protection"))
    ("Competition God" ("All" "Divination" "Elemental" "Air" "Earth" "Fire" "Water") ("Combat" "Healing" "Travel"))
    ("Destiny God" ("All" "Divination" "Guardian" "Protection" "Summoning") ("Combat" "Necromantic" "Sun" "Thought" "Weather"))
    ("Fate God" ("All" "Divination" "Guardian" "Protection" "Summoning") ("Combat" "Necromantic" "Sun" "Thought" "Weather"))
    ("Guardianship God" ("All" "Necromantic" "Protection") ("Guardian" "Healing" "Law"))
    ("Hunting God" ("All" "Divination" "Guardian" "Protection" "Summoning" "Travel") ("Animal" "Healing" "Plant" "Weather"))
    ("Justice God" ("All" "Divination" "Law" "Necromantic") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian"))
    ("Kingship God" ("All" "Charm" "Elemental" "Air" "Earth" "Fire" "Water") ("Healing" "Law" "Protection"))
    ("Magic God" ("All" "Astral" "Charm" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Numbers" "Protection" "Summoning") ("Animal" "Guardian" "Necromantic" "Plant" "Sun" "Weather"))
    ("Messengers God" ("All" "Charm" "Divination" "Protection" "Sun" "Travel") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Necromantic" "Plant"))
    ("Mischief God" ("Chaos" "Charm" "Divination" "Protection" "Summoning") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Plant"))
    ("Oceans God" ("All" "Animal" "Divination" "Water" "Weather") ("Charm" "Combat" "Plant" "Protection" "Travel"))
    ("Prosperity God" ("All" "Animal" "Creation" "Plant" "Summoning" "Wards") ("Guardian" "Healing" "Necromantic" "Protection"))
    ("Revenge God" ("All" "Divination" "Law" "Necromantic") ("Elemental" "Air" "Earth" "Fire" "Water" "Guardian"))
    ("Rivers God" ("All" "Animal" "Divination" "Water" "Weather") ("Charm" "Combat" "Plant" "Protection" "Travel"))
    ("Rulership God" ("All" "Charm" "Elemental" "Air" "Earth" "Fire" "Water") ("Healing" "Law" "Protection"))
    ("Seasons God" ("All" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Protection" "Weather") ("Animal" "Divination" "Healing" "Plant" "Time"))
    ("Strength God" ("All" "Combat" "Healing") ("Elemental" "Air" "Earth" "Fire" "Water" "Necromantic" "War"))
    ("Time God" ("All" "Astral" "Divination" "Healing" "Necromantic" "Time") ("Plant" "Protection" "Sun" "Weather"))
    ("Trade God" ("All" "Charm" "Divination" "Guardian" "Protection") ("Combat" "Healing" "Sun" "Travel" "Weather"))
    ("Trickery God" ("Chaos" "Charm" "Divination" "Protection" "Summoning") ("Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Plant"))
    ("War God" ("Combat" "Healing" "War") ("Necromantic" "Protection"))
    ("Wisdom God" ("All" "Charm" "Divination" "Thought") ("Healing" "Numbers" "Sun"))
    ("Abbathor" ("All" "Charm" "Combat" "Guardian" "Summoning" "Sun") ("Creation" "Divination"))
    ("Berronar Truesilver" ("All" "Combat" "Creation" "Divination" "Earth" "Guardian" "Healing" "Law" "Necromantic" "Protection" "Wards") ("Animal" "Charm"))
    ("Clanggedin" ("All" "Combat" "Guardian" "Law" "Protection" "War") ("Charm" "Earth" "Healing" "Wards"))
    ("Dugmaren" ("All" "Astral" "Charm" "Divination" "Guardian" "Numbers" "Protection" "Thought" "Wards") ("Chaos" "Creation" "Healing"))
    ("Dumathoin" ("All" "Creation" "Earth" "Fire" "Protection" "Wards") ("Combat" "Divination" "Healing" "Travel"))
    ("Gorm Gulthyn" ("All" "Combat" "Divination" "Guardian" "Healing" "Protection" "Sun") ("Animal" "Charm" "Creation" "Earth" "Necromantic" "Summoning"))
    ("Haela Brightaxe" ("All" "Combat" "Guardian" "Healing" "Protection") ("Creation" "Necromantic" "Sun"))
    ("Marthammor Duin" ("All" "Combat" "Creation" "Divination" "Guardian" "Healing" "Protection" "Sun") ("Animal" "Charm" "Earth" "Necromantic" "Plant" "Summoning" "Weather"))
    ("Moradin" ("All" "Combat" "Creation" "Earth" "Fire" "Guardian" "Healing" "Law" "Necromantic" "Protection" "War" "Wards") ("Divination"))
    ("Muamman Duathal" ("All" "Charm" "Creation" "Divination" "Earth" "Guardian" "Protection" "Travel") ("Animal" "Combat" "Air" "Water" "Healing" "Plant" "Summoning" "Sun" "Weather"))
    ("Sharindlar" ("All" "Charm" "Creation" "Divination" "Guardian" "Healing" "Protection" "Sun") ("Combat" "Earth" "Necromantic" "Plant" "Wards"))
    ("Vergadain" ("All" "Charm" "Creation" "Guardian" "Protection") ("Divination" "Healing" "Time" "Travel"))
    ("Laduguer" ("All" "Combat" "Divination" "Earth" "Guardian" "Healing" "Law" "Sun" "Wards") ("Creation" "Necromantic"))
    ("Haela Brightaxe" ("All" "Combat" "Guardian" "Healing" "Protection") ("Creation" "Necromantic" "Sun" "Travel"))
    ("Marthammor Duin" ("All" "Combat" "Creation" "Divination" "Guardian" "Healing" "Protection" "Sun" "Travel") ("Animal" "Charm" "Earth" "Necromantic" "Plant" "Summoning" "Weather"))
    ("Sharindlar" ("All" "Charm" "Creation" "Divination" "Guardian" "Healing" "Protection" "Sun") ("Combat" "Earth" "Necromantic" "Plant" "Wards"))
    ("Thard Harr" ("All" "Combat" "Guardian" "Healing" "Plant" "Protection") ("Animal" "Creation" "Necromantic" "Sun"))
    ("Aerdrie Faenya" ("All" "Animal" "Air" "Protection" "Sun" "Travel" "Weather") ("Charm" "Healing" "Summoning"))
    ("Corellon Larethian" ("All" "Charm" "Combat" "Creation" "Guardian" "Healing" "Necromantic" "Protection" "Sun" "War" "Wards") ("Astral" "Chaos" "Summoning" "Thought"))
    ("Erevan Ilesere" ("All" "Chaos" "Charm" "Creation" "Guardian") ("Healing" "Protection" "Summoning" "Thought"))
    ("Fenmarel Mestarine" ("All" "Animal" "Chaos" "Charm" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Protection" "Sun" "Weather") ("Necromantic"))
    ("Hanali Celanil" ("All" "Charm" "Creation" "Guardian" "Healing" "Necromantic" "Plant" "Protection" "Sun") ("Wards" "Weather"))
    ("Labelas Enoreth" ("All" "Animal" "Astral" "Charm" "Divination" "Numbers" "Plant" "Protection" "Thought" "Time") ("Healing" "Weather"))
    ("Sehanine" ("All" "Astral" "Charm" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Travel") ("Thought" "Wards"))
    ("Solonor Thelandira" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Plant" "Sun" "Weather") ("Healing" "Necromantic"))
    ("Eilistraee" ("All" "Combat" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Protection" "Sun" "Wards" "Weather") ("Animal" "Charm" "Divination" "Plant" "Summoning" "Travel"))
    ("Ghaunadaur" ("All" "Animal" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic") ("Charm" "Creation" "Divination" "Protection" "Summoning"))
    ("Kiaransalee" ("All" "Charm" "Combat" "Divination" "Earth" "Guardian" "Healing" "Necromantic" "Sun") ("Astral" "Chaos"))
    ("Lolth" ("All" "Charm" "Combat" "Creation" "Divination" "Earth" "Water" "Guardian" "Healing" "Necromantic" "Protection" "Summoning" "Sun") ("Animal" "Chaos"))
    ("Vhaerun" ("All" "Charm" "Combat" "Divination" "Air" "Earth" "Guardian" "Healing") ("Creation" "Necromantic" "Protection" "Time"))
    ("Ghaunadaur" ("All" "Animal" "Chaos" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic") ("Charm" "Creation" "Divination" "Protection" "Summoning"))
    ("Deep Sashelas" ("All" "Animal" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Protection" "Wards" "Weather") ("Combat" "Summoning" "Sun"))
    ("Trishina" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Plant" "Protection" "Sun" "Weather") ("Divination"))
    ("Rillifane Rallathil" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Sun" "Time" "Weather") ("Divination"))
    ("Annam" ("All" "Astral" "Charm" "Combat" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Protection" "Summoning" "Sun" "Thought" "Time") ("Necromantic" "Weather"))
    ("Gorellik" ("All" "Animal" "Protection") ("Creation" "Necromantic" "Travel"))
    ("Grolantor" ("All" "Combat" "Earth" "Healing" "Summoning") ("Animal" "Necromantic" "Sun" "War"))
    ("Hiatea" ("All" "Animal" "Creation" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Protection" "Summoning" "Sun" "Weather") ("Combat" "Divination" "Necromantic" "Travel" "Wards"))
    ("Iallanis" ("All" "Creation" "Guardian" "Healing" "Protection" "Sun" "Wards") ("Animal" "Necromantic" "Plant" "Time"))
    ("Karontor" ("All" "Animal" "Combat" "Healing" "War") ("Protection" "Sun"))
    ("Memnor" ("All" "Astral" "Charm" "Divination" "Summoning" "Sun") ("Numbers" "Thought" "Time"))
    ("Skoraeus Stonebones" ("All" "Creation" "Earth" "Guardian" "Healing" "Protection" "Summoning" "Wards") ("Animal" "Necromantic"))
    ("Stronmaus (Cloud G)" ("All" "Animal" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Summoning" "Sun" "Weather") ("Charm" "Combat" "Necromantic"))
    ("Stronmaus (Storm G)" ("All" "Animal" "Creation" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Summoning" "Sun" "Weather") ("Charm" "Combat" "Necromantic" "Protection" "Thought" "Time"))
    ("Vaprak" ("All" "Combat" "Divination" "Healing" "Protection" "Sun") ())
    ("Yeenoghu" ("All" "Chaos" "Combat" "Protection" "Summoning") ("Guardian" "Healing" "Sun"))
    ("Baervan" ("All" "Animal" "Charm" "Earth" "Water" "Healing" "Plant" "Sun" "Travel" "Weather") ("Divination"))
    ("Baravar Cloakshadow" ("All" "Creation" "Guardian" "Protection") ("Astral" "Charm" "Healing" "Travel"))
    ("Flandal Steelskin" ("All" "Creation" "Earth" "Fire" "Guardian" "Protection") ("Divination" "Healing"))
    ("Gaerdal Ironhand" ("All" "Combat" "Guardian" "Protection") ("Divination" "Healing" "War" "Wards"))
    ("Garl Glittergold" ("All" "Animal" "Charm" "Combat" "Creation" "Earth" "Guardian" "Healing" "Necromantic" "Plant" "Protection" "Wards") ("Divination" "Sun" "Weather"))
    ("Nebelun" ("All" "Creation" "Divination" "Thought" "Time") ("Chaos" "Charm" "Guardian" "Healing" "Protection"))
    ("Segojan Earthcaller" ("All" "Animal" "Earth" "Guardian" "Plant" "Protection") ("Divination" "Healing" "Sun" "Travel" "Wards"))
    ("Urdlen" ("All" "Combat" "Earth" "Healing" "Sun") ("Animal" "Chaos" "Necromantic" "Summoning"))
    ("Calladuran" ("All" "Charm" "Creation" "Earth" "Healing" "Protection" "Wards") ("Combat" "Divination" "Necromantic"))
    ("Kuraulyek" ("All" "Animal" "Charm" "Air" "Guardian" "Sun") ("Combat" "Divination" "Healing"))
    ("Grankhul" ("All" "Animal" "Combat" "Earth" "Water" "Guardian") ("Chaos" "Protection" "Sun" "Travel" "Weather"))
    ("Hruggek" ("All" "Combat" "Guardian" "Protection" "Summoning" "Sun") ("Creation" "Divination" "War"))
    ("Bargrivyek" ("All" "Divination" "Air" "Earth" "Guardian" "Protection") ("Charm" "Combat" "Healing" "War" "Wards"))
    ("Khurgobaeyag" ("All" "Combat" "Healing" "Protection" "Sun") ("Charm" "Necromantic"))
    ("Maglubiyet" ("All" "Combat" "Divination" "Healing" "Necromantic" "Sun" "War") ("Charm" "Creation" "Guardian" "Protection" "Summoning" "Wards"))
    ("Nomog-Geaya" ("All" "Combat" "Healing" "Necromantic" "Protection" "Sun" "War") ("Creation"))
    ("Goblin Shaman" ("Divination" "Healing" "Protection" "Sun") ())
    ("Gaknulak" ("All" "Charm" "Divination" "Air" "Earth" "Guardian" "Protection" "Wards") ("Combat" "Summoning"))
    ("Kurtulmak" ("All" "Combat" "Earth" "Protection" "Summoning" "Sun" "War") ("Divination" "Healing" "Necromantic" "Wards"))
    ("Bahgtru" ("All" "Combat" "Healing" "Protection" "Summoning" "War") ())
    ("Gruumsh" ("All" "Combat" "Law" "Summoning" "Sun" "War") ("Divination" "Earth" "Fire" "Healing" "Necromantic" "Protection" "Wards"))
    ("Ilneval" ("All" "Combat" "Sun" "War") ("Creation" "Guardian" "Protection" "Summoning" "Wards"))
    ("Luthic" ("All" "Creation" "Earth" "Guardian" "Healing" "Protection" "Sun") ("Charm" "Combat" "Necromantic"))
    ("Shargaas" ("All" "Combat" "Healing" "Sun") ("Creation" "Earth" "Travel"))
    ("Yurtrus" ("All" "Healing" "Necromantic") ("Combat" "Protection" "Summoning" "Sun"))
    ("Arvoreen" ("All" "Combat" "Guardian" "Healing" "Protection" "Sun" "War" "Wards") ("Law" "Necromantic" "Summoning"))
    ("Brandobaris" ("All" "Charm" "Creation" "Protection") ("Animal" "Combat" "Divination" "Guardian" "Healing"))
    ("Cyrrollalee" ("All" "Animal" "Creation" "Guardian" "Healing" "Protection" "Wards") ("Combat" "Divination" "Necromantic" "Plant" "Sun"))
    ("Sheela Peryroyl" ("All" "Animal" "Creation" "Air" "Earth" "Water" "Healing" "Plant" "Sun" "Travel" "Weather") ("Charm" "Divination" "Guardian" "Necromantic" "Protection"))
    ("Urogalan" ("All" "Divination" "Earth" "Guardian" "Healing" "Necromantic" "Protection") ("Time" "Weather"))
    ("Yondalla" ("All" "Animal" "Combat" "Creation" "Divination" "Air" "Earth" "Water" "Guardian" "Healing" "Law" "Necromantic" "Plant" "Protection" "Sun" "Wards") ("Weather"))
    ("Meriadar" ("All" "Charm" "Divination" "Guardian" "Healing" "Law" "Protection" "Thought" "Wards") ("Astral" "Creation" "Necromantic" "Plant" "Time"))
    ("Ogre Shaman" () ("Combat" "Divination" "Healing" "Protection" "Sun"))
    ("Oracle" ("All" "Divination" "Protection" "Sun") ("Charm" "Guardian" "Healing" "Necromantic"))
    ("Thoul Shaman" () ("Charm" "Healing" "Necromantic"))
    ("War Priest" ("All" "Combat" "Healing" "Protection") ("Divination" "Guardian" "Necromantic" "Sun"))
    ("Blibdoolpoolp" ("All" "Combat" "Divination" "Earth" "Water" "Sun") ("Charm" "Healing" "Necromantic" "War" "Weather"))
    ("Demogorgon" ("All" "Combat" "Divination" "Healing" "Necromantic" "Sun") ("Animal" "Chaos" "Guardian" "Protection" "Summoning"))
    ("Eadro" ("All" "Creation" "Divination" "Water" "Guardian" "Healing" "Necromantic" "Protection" "Summoning") ("Animal" "Combat"))
    ("Laogzed" ("All" "Animal" "Combat" "Necromantic" "Plant" "Protection") ())
    ("Merrshaulk" ("All" "Animal" "Divination" "Healing" "Plant") ("Chaos" "Charm" "Combat"))
    ("Panzuriel" ("All" "Combat" "Divination" "Earth" "Water" "Healing" "Sun" "War") ("Animal" "Charm" "Summoning"))
    ("Persana" ("All" "Animal" "Creation" "Divination" "Water" "Healing" "Necromantic" "Protection" "Summoning") ("Charm" "Combat" "Wards"))
    ("Ramenos" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Weather") ("Divination"))
    ("Sekolah" ("All" "Combat" "Healing" "Protection" "War") ("Animal"))
    ("Semuanya" ("All" "Animal" "Healing" "Plant") ("Combat" "Divination" "Necromantic" "Protection" "Weather"))
    ("Sess'innek" ("All" "Combat" "Water" "Necromantic" "Summoning" "Sun") ("War"))
    ("Surminare" ("All" "Animal" "Charm" "Creation" "Divination" "Healing" "Protection" "Weather") ("Necromantic" "Wards"))
    ("Beholder Mother" ("All" "Astral" "Combat" "Divination" "Necromantic" "Numbers" "Protection" "Thought" "Time") ())
    ("Dark God" ("All" "Astral" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Numbers" "Sun" "Thought" "Time") ("Charm" "Wards"))
    ("Elder Elemental God" ("All" "Astral" "Combat" "Divination" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Necromantic" "Numbers" "Sun") ("Weather"))
    ("Juiblex" ("All" "Charm" "Divination" "Earth" "Water" "Healing" "Necromantic" "Summoning") ("Combat" "Numbers"))
    ("Maanzecorian" ("All" "Astral" "Charm" "Divination" "Law" "Numbers" "Sun" "Thought" "Time") ())
    ("Psilofyr" ("All" "Astral" "Creation" "Divination" "Earth" "Water" "Guardian" "Healing" "Law" "Numbers" "Protection" "Thought" "Wards") ("Necromantic"))
    ("Quorlinn" ("All" "Chaos" "Creation" "Divination" "Plant" "Weather") ("Animal" "Charm" "Healing"))
    ("Skerrit" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Healing" "Plant" "Protection" "Sun" "Weather") ("Divination"))
    ("Squerrik" ("All" "Animal" "Charm" "Necromantic" "Sun") ())
    ("Syranita" ("All" "Animal" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Plant" "Protection" "Sun" "Weather") ("Divination"))
    ("Dracon Cleric" ("Animal" "Combat" "Creation" "Divination" "Guardian" "Healing" "Necromantic" "Protection" "Sun") ())
    ("Scro Cleric" ("All" "Charm" "Combat" "Elemental" "Air" "Earth" "Fire" "Water" "Guardian" "Healing" "Protection" "Summoning") ())))
